### PR TITLE
New York Times clone page

### PR DESCRIPTION
**Pull request by ad9311**
Finished the top bar and main article, including font styling, images and colors. Set up the bottom portion of the article, still unfinished.

### CODE REVIEW

**Review by eypsrcnuygr — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 

Hello @ad9311. I've checked your page and it looks good. :+1: However as you mentioned in your additional information there are some parts that need to be implemented. I'm giving a list below, please check them and implement them.

- [x] On your more in space and astronomy part, there are no gaps between the pictures. Please give some margin between them.
- [x]  As you know, there is no footer on your page. Please implement it with the given fonts and the style.
- [ ]  Please don't forget the links at the bottom below the footer. I wanted to remind you that because sometimes the students can skip this part.

Apart from those issues, your page looks good and satisfies the requirements. :muscle: 
Please address those issues and when you finish submit for a re-review.
As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have 2 code reviews left for this project.
If you have any questions about the review, feel free to reach out to me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Comment by ad9311** [comment]
Made this changes into index.html and master.css:
- Applied margin to newsletters and editor's pick content
- Applied font styling and colors
- Fixed typos
- Added footer
- Added links at the very bottom

Please let me know about these corrections. **Thank you!**  🙂

**Review by christianotieno — APPROVED** [review]
## Project Approved 🍾 
Hello @ad9311 👋🏾 
Congratulations. The project is now approved. 👏🏾 
All the very best in your next tasks 🥇 
Before we merge do you mind having a look at the following optional changes? 👇🏾 

#### Optional Changes 
- [x] Do you mind adding a live link and a screenshot of the page to the README? I wills share this [template]([url](https://github.com/microverseinc/readme-template)) as inspiration should you pick this up.
- [x] It would be nice if the page had the fixed footer (that sticks to the bottom part of the screen) gets implemented. ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html))




### Happy coding 💻 
#### Christian Otieno (CR)

**Comment by ad9311** [comment]
Thank you for reviewing my code. 😃
I followed your suggestions and made the optional changes. 👍🏽
- Live page is available in the **README** file 📄
- Two screenshots have been added as well 📷
---

> ## Project Approved champagne
> 
> Hello @ad9311 👋🏾
> Congratulations. The project is now approved. 👏🏾
> All the very best in your next tasks 1st_place_medal
> Before we merge do you mind having a look at the following optional changes? 👇🏾
> #### Optional Changes
> 
>     * [x]  Do you mind adding a live link and a screenshot of the page to the README? I wills share this template as inspiration should you pick this up.
> 
>     * [x]  It would be nice if the page had the fixed footer (that sticks to the bottom part of the screen) gets implemented. ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html))
> 
> 
> ### Happy coding 💻
> #### Christian Otieno (CR)

**Pull request closed without merging**
